name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Source Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Clone Config Repository
        uses: actions/checkout@v2
        with:
          repository: Linear-finance/linear-buildr-config
          ref: master
          token: ${{ secrets.CONFIG_REPO_TOKEN }}
          path: ./configs

      - name: Apply Configuration
        run: |
          REPO_ROOT=$(pwd)
          ./configs/apply.sh production "${REPO_ROOT}"

      - name: Build Website
        run: |
          yarn generate

      - name: Clone Workers Site Template
        run: |
          git clone https://github.com/xJonathanLEI/cf-workers-site-template

      - name: Install Template Dependencies
        run: |
          cd ./cf-workers-site-template
          npm install

      - name: Authenticate with Cloudflare
        run: |
          cd ./cf-workers-site-template
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | yarn wrangler config

      - name: Configure Proxy
        run: |
          cp ./configs/proxies.json ./cf-workers-site-template/src/external/proxies.json

      - name: Publish Workers Site
        env:
          CLOUDFLARE_WORKER_NAME: ${{ secrets.CLOUDFLARE_WORKER_NAME }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          rm -rf ./cf-workers-site-template/public/**
          cp -r ./dist/. ./cf-workers-site-template/public/
          cd ./cf-workers-site-template
          yarn run publish
